name: Terraform Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment (dev / uat / prod)"
        required: true
        default: "dev"

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init -input=false -backend-config=enviornments/${{ github.event.inputs.environment }}/backend.tfvars

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan -input=false -var-file=enviornments/${{ github.event.inputs.environment }}/${{ github.event.inputs.environment }}.tfvars

      - name: Show Plan Output
        run: terraform show tfplan

      # ðŸ‘‡ Manual approval step before apply
      - name: Wait for approval
        uses: trstringer/manual-approval@v1
        with:
          approvers: ${{ github.actor }}   # only you can approve, can add more
          instructions: "Review the Terraform plan above. Approve to proceed with apply."

      - name: Terraform Apply
        run: terraform apply -input=false tfplan
